### ISSUE TITLE
custom-webpack: update from 12.1.3  to 13.0.0: dies on typescript files

### ISSUE THREAD

**Issue by mduft** [just-jeb/angular-builders#1062]
## Describe the Bug

I updated our app from angular 12 to 13. We're using cypress.io for UI tests and want to instrument the application prior to tests using istanbul. There is a custom webpack config to do so. This worked fine until now, using custom-webpack 12.1.3 - also having *all* other packages updated to latest now. However once updating custom-webpack to 13.0.0 the build fails on *all* typescript files:

```
./src/main.ts - Error: Module build failed (from ./node_modules/@jsdevtools/coverage-istanbul-loader/lib/index.js):
Error: E:\other\tmp\deployment\ui\webapp\src\main.ts: don't know how to turn this value into a node
    at valueToNode (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\types\lib\converters\valueToNode.js:98:9)
    at Object.valueToNode (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\types\lib\converters\valueToNode.js:92:58)
    at Object.exit (E:\other\tmp\deployment\ui\webapp\node_modules\@jsdevtools\coverage-istanbul-loader\node_modules\istanbul-lib-instrument\dist\visitor.js:641:30)
    at PluginPass.exit (E:\other\tmp\deployment\ui\webapp\node_modules\@jsdevtools\coverage-istanbul-loader\node_modules\istanbul-lib-instrument\dist\instrumenter.js:104:29)
    at newFn (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\traverse\lib\visitors.js:177:21)
    at NodePath._call (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\traverse\lib\path\context.js:111:8)
    at TraversalContext.visitQueue (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\traverse\lib\context.js:103:16)
    at TraversalContext.visitSingle (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\traverse\lib\context.js:77:19)
    at TraversalContext.visit (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\traverse\lib\context.js:131:19)
    at Function.traverse.node (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\traverse\lib\index.js:82:17)
    at traverse (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\traverse\lib\index.js:62:12)
    at transformFile (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\core\lib\transformation\index.js:105:29)
    at transformFile.next (<anonymous>)
    at run (E:\other\tmp\deployment\ui\webapp\node_modules\@babel\core\lib\transformation\index.js:33:12)
```

## Minimal Reproduction

Using NodeJS 16 LTS:

```
git clone https://github.com/bdeployteam/bdeploy.git
cd bdeploy
git checkout -b angular13 -t origin/angular13
./gradlew genDtos
cd ui/webapp
npm install
npx ng serve -c cov-standalone
```

This will *work* using 12.0.1 - you should get a running angular server. Looking at the outdated packages:

```
.../bdeploy/ui/webapp $ npm outdated
Package                           Current  Wanted  Latest  Location                                       Depended by
@angular-builders/custom-webpack   12.1.3  12.1.3  13.0.0  node_modules/@angular-builders/custom-webpack  webapp
typescript                          4.4.4   4.4.4   4.5.2  node_modules/typescript                        webapp
.../bdeploy/ui/webapp $ npm install @angular-builders/custom-webpack@13.0.0
removed 290 packages, changed 1 package, and audited 1639 packages in 3s
```

Now, the above exception will happen when trying to build the application (on every .ts file) with the same command:

```
.../bdeploy/ui/webapp $ npx ng serve -c cov-standalone
[...]
./src/main.ts - Error: Module build failed (from ./node_modules/@jsdevtools/coverage-istanbul-loader/lib/index.js):
Error: E:\other\tmp\bdeploy\ui\webapp\src\main.ts: don't know how to turn this value into a node
    at valueToNode (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\types\lib\converters\valueToNode.js:98:9)
    at Object.valueToNode (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\types\lib\converters\valueToNode.js:92:58)
    at Object.exit (E:\other\tmp\bdeploy\ui\webapp\node_modules\@jsdevtools\coverage-istanbul-loader\node_modules\istanbul-lib-instrument\dist\visitor.js:641:30)
    at PluginPass.exit (E:\other\tmp\bdeploy\ui\webapp\node_modules\@jsdevtools\coverage-istanbul-loader\node_modules\istanbul-lib-instrument\dist\instrumenter.js:104:29)
    at newFn (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\traverse\lib\visitors.js:177:21)
    at NodePath._call (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\traverse\lib\path\context.js:111:8)
    at TraversalContext.visitQueue (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\traverse\lib\context.js:103:16)
    at TraversalContext.visitSingle (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\traverse\lib\context.js:77:19)
    at TraversalContext.visit (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\traverse\lib\context.js:131:19)
    at Function.traverse.node (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\traverse\lib\index.js:82:17)
    at traverse (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\traverse\lib\index.js:62:12)
    at transformFile (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\core\lib\transformation\index.js:105:29)
    at transformFile.next (<anonymous>)
    at run (E:\other\tmp\bdeploy\ui\webapp\node_modules\@babel\core\lib\transformation\index.js:33:12)
[...]
```

## Expected Behavior

The build result should not change when updating.

## Environment

<pre><code>
Libs
- @angular/core version: 13.0.2
- @angular-devkit/build-angular version: 13.0.3
- @angular-builders/custom-webpack version: 13.0.0

For Tooling issues:
- Node version: XX  v16.13.0
- Platform:  Windows

Others:

</code></pre>

**Comment by just-jeb** [comment]
Hello. It's very hard to tell what's going on here without a reproduction. Care to create one?

**Comment by just-jeb** [comment]
Updating `custom-webpack` builder to 13, removing `package-lock` and reinstalling dependencies fixes the issue.
