### ISSUE TITLE
v13 + istanbul-lib-coverage - Don't know how to turn this value into a node

### ISSUE THREAD

**Issue by LukasKlement** [just-jeb/angular-builders#1066]
## Describe the Bug

When upgrading from v12.1.3 to v13.0.0 of this library, end to end test with coverage reporting and code instrumenting (using @jsdevtools/coverage-istanbul-loader and istanbul-lib-coverage)  fails, throwing the following error:

```
Error: /Users/projectpath/src/polyfills.ts: don't know how to turn this value into a node
    at valueToNode (/Users/projectpath/node_modules/@babel/types/lib/converters/valueToNode.js:98:9)
    at Object.valueToNode (/Users/projectpath/node_modules/@babel/types/lib/converters/valueToNode.js:92:58)
    at Object.exit (/Users/projectpath/node_modules/istanbul-lib-instrument/dist/visitor.js:641:30)
    at PluginPass.exit (/Users/projectpath/node_modules/istanbul-lib-instrument/dist/instrumenter.js:104:29)
    at newFn (/Users/projectpath/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/projectpath/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/projectpath/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/projectpath/node_modules/@babel/traverse/lib/path/context.js:111:8)
    at TraversalContext.visitQueue (/Users/projectpath/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitSingle (/Users/projectpath/node_modules/@babel/traverse/lib/context.js:77:19)
    at TraversalContext.visit (/Users/projectpath/node_modules/@babel/traverse/lib/context.js:131:19)
    at Function.traverse.node (/Users/projectpath/node_modules/@babel/traverse/lib/index.js:82:17)
    at traverse (/Users/projectpath/node_modules/@babel/traverse/lib/index.js:62:12)
    at transformFile (/Users/projectpath/node_modules/@babel/core/lib/transformation/index.js:105:29)
    at transformFile.next (<anonymous>)
    at run (/Users/projectpath/node_modules/@babel/core/lib/transformation/index.js:33:12)
```

## Minimal Reproduction

Here's a repo to reproduce the error: https://github.com/LukasKlement/angular-cypress-coverage-tutorial
In the repo, the angular-builders version is fixed to 12.1.3 and it works (e.g. run ng e2e), when upgrading to 13.0.0, the above error is thrown.

## Environment

<pre><code>
Libs
- @angular/core version: 13.0.2
- @angular-devkit/build-angular version: 13.0.3
- @angular-builders/custom-webpack version: 13.0.0

For Tooling issues:
- Node version: 16.13.0
- Platform: Mac

**Comment by just-jeb** [comment]
Same as #1062?

**Comment by LukasKlement** [comment]
Indeed, same problem.

**Comment by just-jeb** [comment]
Updating `custom-webpack` builder to 13, removing `package-lock` and reinstalling dependencies fixes the issue.
