### ISSUE TITLE
custom-webpack:server errors with Cannot read properties of undefined (reading 'colors')

### ISSUE THREAD

**Issue by sir-captainmorgan21** [just-jeb/angular-builders#1311]
## Describe the Bug

When using the @angular-builders/custom-webpack:server builder, it is erroring with the following error.

```
TypeError: Cannot read properties of undefined (reading 'colors')
    at statsToString (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-angular/src/webpack/utils/stats.js:193:32)
    at webpackStatsLogger (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-angular/src/webpack/utils/stats.js:374:17)
    at MergeMapSubscriber.project (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-angular/src/builders/server/index.js:93:44)
    at MergeMapSubscriber._tryNext (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-webpack/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-webpack/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-webpack/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-webpack/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-webpack/node_modules/rxjs/internal/operators/switchMap.js:85:26)
    at SimpleInnerSubscriber._next (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-webpack/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-webpack/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /Users/zach.morgan/Development/mfe-universal/node_modules/@angular-devkit/build-webpack/src/webpack/index.js:58:25
    at /Users/zach.morgan/Development/mfe-universal/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/zach.morgan/Development/mfe-universal/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
```

If I dont specify a `customWebpackConfig`, it works fine. However, as soon as I specify one, it errors. Even if the custom webpack config is essentially empty.

## Minimal Reproduction

I kept the original `server` target and created a `server-custom` target for the repro.

https://github.com/sir-captainmorgan21/angular-builders-custom-webpack-sever-repro

## Expected Behavior

I'd expect this to run without errors.

## Environment

<pre><code>
Libs
- @angular/core version: ~14.2.0
- @angular-devkit/build-angular version: ~14.2.0
- @angular-builders/custom-webpack version: ^14.0.1

**Comment by just-jeb** [comment]
Please try deleting the lock file and node_modules and regenerating it by running clean install.

**Comment by sir-captainmorgan21** [comment]
@just-jeb did doing this with the reproduction repo I supplied work for you?

**Comment by arturovt** [comment]
@sir-captainmorgan21 well, it definitely will error because you're returning an empty config from the function :)

```js
// custom-webpack.config.js
module.exports = () => {
  return {};
};
```

**Comment by sir-captainmorgan21** [comment]
@arturovt I'd have to disagree. This builder merges that returned obj with the default angular server one. It errors whether its empty or not.

**Comment by sir-captainmorgan21** [comment]
@just-jeb deleted package-lock and nodeu modules and ran `npm install`. Also tried `npm ci`, neither resolved the issue. Were you able to reproduce this using the repro issue and resolve it?

**Comment by sir-captainmorgan21** [comment]
Also for reference, someone else seemed to have this issue a while back: https://github.com/angular/angular-cli/issues/16043

**Comment by arturovt** [comment]
It merges when it exports an object, but it doesn’t merge when it exports a factory function: https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/src/custom-webpack-builder.ts#L48

**Comment by sir-captainmorgan21** [comment]
@just-jeb that was it. Thanks! I actually re-read through your docs, and was able to find that. May be a good place for a trouble shooting section though.

**Comment by sir-captainmorgan21** [comment]
and @arturovt Sorry. You are right. Thanks guys
