### ISSUE TITLE
jest-preset-angular Cannot find module 'zone.js/bundles/zone-testing-bundle.umd' 

### ISSUE THREAD

**Issue by chimurai** [just-jeb/angular-builders#1513]
## Describe the Bug

Compatibility issue with `angular 17.0.0-rc.2`

```shell
    Cannot find module 'zone.js/bundles/zone-testing-bundle.umd' from 'node_modules/@angular-builders/jest/node_modules/jest-preset-angular/setup-jest.js'

    Require stack:
      node_modules/@angular-builders/jest/node_modules/jest-preset-angular/setup-jest.js
      node_modules/@angular-builders/jest/dist/jest-config/setup.js

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (node_modules/@angular-builders/jest/src/jest-config/setup.ts:1:1)
```

## Minimal Reproduction

Use `@angular-builders/jest@latest` with `angular 17.0.0-rc.2`

## Expected Behavior

jest tests should pass

## Environment

<pre><code>
Libs
- @angular/core version: 17.0.0-rc.2
- @angular-devkit/build-angular version: 17.0.0-rc.2
- @angular-builders/jest} version: 16.0.0

For Tooling issues:
- Node version: 18  
- Platform:  Mac, Linux

Others:

</code></pre>

## Additional Context

Related to https://github.com/just-jeb/angular-builders/issues/1512

**Comment by chimurai** [comment]
update to `@angular-builders/jest@16.0.2-beta.3` to fix the issue
