### ISSUE TITLE
REGRESSION: Upgrading from "@angular-builders/jest": "18.0.0" to "19.0.0-beta.1" makes half of our tests fail

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [just-jeb/angular-builders#1892]
## Describe the Bug

As the title says, trying to upgrade this package to "19.0.0-beta.1" makes 25 of our 61 test suites fail.
This because of a circular reference in our imports.
However until now, building for angular or jest has never been an issue.
It seems something changed in the configuration of this package that does this?

## Environment

Libs
- @angular/core version: 19.0.3
- @angular-devkit/build-angular version: 19.0.3
- @angular-builders/jest version: 19.0.0-beta.1

## Errors:

I'm indicating with ** where the circular references are:

 FAIL  tests/app/generic-competitions/ranking-prints.spec.ts
  ● Test suite failed to run

    ReferenceError: Cannot access 'ToastService' before initialization

       6 |
       7 | @Injectable({ providedIn: 'root' })
    >  8 | export class ToastService {
         |         ^
       9 |   private overlayRef: OverlayRef;
      10 |   private toastContainerRef: ComponentRef<ToastContainerComponent>;
      11 |

      **at Object.get [as ToastService] (../src/app/generic-components/toast/toast.service.ts:8:9)**
      at Object.<anonymous> (../src/app/generic-components/toast/toast.component.ts:138:30)
      at Object.<anonymous> (../src/app/generic-components/toast/toast-container.component.ts:12:25)
      **at Object.<anonymous> (../src/app/generic-components/toast/toast.service.ts:14:34)**
      at Object.<anonymous> (../src/app/core/services/helpers.service.ts:30:23)
      at Object.<anonymous> (../src/app/core/services/authentication.service.ts:13:25)
      at Object.<anonymous> (../src/app/core/services/data-model-services/user.service.ts:13:32)
      at Object.<anonymous> (../src/app/core/services/data-model-services/manager.service.ts:12:22)
      at Object.<anonymous> (../src/app/core/services/data-model-services/organisation.service.ts:12:25)
      at Object.<anonymous> (../src/app/scoring/ranking.service.ts:13:30)
      at Object.<anonymous> (tests/app/generic-competitions/ranking-prints.spec.ts:8:25)

 FAIL  tests/app/helpers.service.spec.ts
  ● Test suite failed to run

    ReferenceError: Cannot access 'Helpers' before initialization

       6 | import { Communication } from './communication.service';
       7 | import { AggregationModel } from '../../../../shared/models/aggregation.model';
    >  8 | import { IpInfoModel } from '../models/IpInfoModel';
         |         ^
       9 | import { HttpClient } from '@angular/common/http';
      10 | import { InformationPanelComponent } from '../../generic-components/information-panel/information-panel.component';
      11 | import { DecimalPipe, DOCUMENT } from '@angular/common';

      **at Object.get [as Helpers] (../src/app/core/services/helpers.service.ts:8:9)**
      at Object.<anonymous> (../src/app/core/services/firebase-analytics.service.ts:79:32)
      at Object.<anonymous> (../src/app/core/services/authentication.service.ts:17:35)
      **at Object.<anonymous> (../src/app/core/services/helpers.service.ts:13:32)**
      at Object.<anonymous> (../e2e-testing/utils/mock-services/mock-helpers.ts:11:25)
      at Object.<anonymous> (tests/app/helpers.service.spec.ts:6:22)

**Comment by vsarangan** [comment]
Hi @LanderBeeuwsaert , I have a question—have you tried the same approach in an Angular 19 application? Does the Angular 19 build work with this package?

**Comment by LanderBeeuwsaert** [comment]
Hi @vsarangan , I think you're asking if building the angular application itself still works, correct?
If so yes, ng serve and ng build, both dev version and prod version still work normally.

**Comment by vsarangan** [comment]
Hi @LanderBeeuwsaert ,One more query 
I have an Angular 19 application, and I'm trying to use a custom builder library. Officially, the library supports Angular 18, which I was able to install. Is this combination working for you? In my case, I can successfully build the project, but when using it as a web component in a different application, I encounter runtime errors.

**Comment by LanderBeeuwsaert** [comment]
@vsarangan I have no idea how to answer your question. In what way is this related to this bug ticket?

**Comment by just-jeb** [comment]
I assume the issue is no longer and can be closed?

**Comment by LanderBeeuwsaert** [comment]
@just-jeb in a way, we reverted to the plain jest packages which resolved our issue. I'll close
