### ISSUE TITLE
Allow Config Function To Return Promise

### ISSUE THREAD

**Issue by daniel-nagy** [just-jeb/angular-builders#274]
**Is your feature request related to a problem? Please describe.**
Yes, I can't do something asynchronous in my config function.

**Describe the solution you'd like**
Allow the config function to return a promise, e.g.

```typescript
module.exports = async (config, options) => {
  return config;
}
```

**Additional context**
@angular-builders/custom-webpack `v7.4.3`

**Comment by meltedspark** [comment]
Reasonable request, will do.

**Comment by daniel-nagy** [comment]
Just took a look at the source code, I think `BrowserBuilder#buildWebpackConfig` would need to be updated to allow returning a `Promise` in the **@angular-devkit/build-angular** package.

**Comment by meltedspark** [comment]
Yep, you're right, and it won't happen (not in the way you imagine). They are rewriting it completely now
and with the new Angular CLI 8 which is supposed to be out mid April it would be a piece of cake.  
Version 8 of `custom-webpack` builder will be released at the same time so if you don't mind to wait it will be available pretty soon. You can catch a glimpse of the new implementation [here](https://github.com/meltedspark/angular-builders/blob/new-architect-api/packages/custom-webpack/src/browser/index2.ts).

**Comment by daniel-nagy** [comment]
So in version 8 there will be a config transform function that returns an Observable?

**Comment by meltedspark** [comment]
In a nutshell, yes.

**Comment by johanndev** [comment]
I'm not clear on the status of this issue - is this functionality implemented in the latest version? Anyways, here is what I'm trying to do:

Version info: 
```
"@angular-builders/custom-webpack": "^8.2.0"
"@angular/cli": "^8.3.8",
```
I'd like to use this builder to replace a string during the build process of my angular app.

My `extra-webpack.config.js`:
```typescript
var StringReplacePlugin = require("string-replace-webpack-plugin");
const nbgv = require('nerdbank-gitversioning');

const configPromise = async function() {
  const currentVersion = await nbgv.getVersion();
  return {
    module: {
      rules: [{
        exclude: /node_modules/,
        use: StringReplacePlugin.replace({
          replacements: [{
            pattern: /<%CURRENT_VERSION_HERE%>/,
            replacement: function (match, p1, offset, string) {
              return currentVersion.simpleVersion
            }
          }]
        })
      }]
    },
    plugins: [
      new StringReplacePlugin()
    ]
  };
};

module.exports = configPromise
```

Unfortunately the build fails with: 
```
> my-ng-app@0.0.0 build C:\Path\to\my\project\src\My.Project\ClientApp
> ng build

C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\stats.js:43
    const colors = statsConfig.colors;
                               ^

TypeError: Cannot read property 'colors' of undefined
    at Object.statsToString (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\stats.js:43:32)
    at C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\@angular-devkit\build-angular\src\browser\index.js:43:33
    at callback (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:33:13)
    at finalCallback (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\webpack\lib\Compiler.js:257:39)
    at hooks.done.callAsync.err (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\webpack\lib\Compiler.js:273:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\tapable\lib\Hook.js:154:20)
    at onCompiled (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\webpack\lib\Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\webpack\lib\Compiler.js:671:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\tapable\lib\Hook.js:154:20)
    at compilation.seal.err (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\webpack\lib\Compiler.js:668:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\webpack\lib\Compilation.js:1385:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Path\to\my\project\src\My.Project\ClientApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
```

**Comment by just-jeb** [comment]
It is not implemented yet, therefore the error I believe. I plan to add it soon but as always PRs are welcome.
