### ISSUE TITLE
Jest Integration with angular 8. The "id" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by anuragmca90** [just-jeb/angular-builders#429]
I am using the angular 8.2.0 and i am trying to configure the jest:
https://github.com/just-jeb/angular-builders/tree/master/packages/jest
 

But when I am running the `ng test` I am getting the validation error.

> Preset jest-preset-angular is invalid:
> The "id" argument must be of type string. Received type object
> TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
> at validateString (internal/validators.js:125:11)
>     at Module.require (internal/modules/cjs/loader.js:687:3)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at setupPreset (U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules\jest-config\build\normalize.js:219:14)
>     at normalize (U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules\jest-config\build\normalize.js:544:15)
>     at readConfig (U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules\jest-config\build\index.js:163:46)
>     at readConfigs (U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules\jest-config\build\index.js:372:26)
>     at U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules\@jest\core\build\cli\index.js:155:58
>     at Generator.next (<anonymous>)
>     at asyncGeneratorStep (U:\Proj\Event-Browser-New\np-3\br-events-ui\node_modules\@jest\core\build\cli\index.js:108:24)

Could you please help me to fix this issue?
![Untitled](https://user-images.githubusercontent.com/6928765/62545502-754f4f00-b87f-11e9-9a12-7be7c92eac15.png)

**Comment by just-jeb** [comment]
Closing this — it was filed against Angular 8 and has had no activity in 6+ years. If you're hitting a similar issue on a current version, please open a new issue.
