### ISSUE TITLE
Error when migrating to Angular 9

### ISSUE THREAD

**Issue by ssg127** [just-jeb/angular-builders#809]
I have updated the project to angular 9, including @ angular-builders / custom-webpack with the above configuration not working for me. Do I have to make any additional changes? I can't find any information

Mi package.json is:

```
{
  "name": "elcano-web-elements",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --port 4206",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build:elements": "ng build --prod --output-hashing none && node elements-build.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.12",
    "@angular/cdk": "~9.2.4",
    "@angular/common": "~9.1.12",
    "@angular/compiler": "~9.1.12",
    "@angular/core": "~9.1.12",
    "@angular/elements": "^9.1.12",
    "@angular/flex-layout": "9.0.0-beta.31",
    "@angular/forms": "~9.1.12",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "~9.1.12",
    "@angular/platform-browser-dynamic": "~9.1.12",
    "@angular/router": "~9.1.12",
    "@ngx-translate/core": "^12.1.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@webcomponents/webcomponentsjs": "^2.4.1",
    "document-register-element": "^1.7.2",
    "ngx-build-plus": "^9.0.4",
    "rxjs": "~6.6.2",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^9.2.0",
    "@angular-devkit/build-angular": "~0.901.12",
    "@angular/cli": "~9.1.12",
    "@angular/compiler-cli": "~9.1.12",
    "@angular/language-service": "~9.1.12",
    "@babel/compat-data": "~7.8.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "concat": "^1.0.3",
    "fs-extra": "^8.1.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.8.3"
  }
}
```

My build task:
`"build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "src/extra-webpack.config.js",
              "mergeStrategies": {
                "externals": "replace"
              }
            },`

My extra-webpack.config.js:

`module.exports = {
  output: {
    jsonpFunction: 'webpackTryElements',
    library: 'tryelements'
  }
};
`

I can do ng start and It's ok, but whne I try to build I get this:

`ERROR in polyfills-es5.2ce58322c0c02b51d655.js from Terser
Invalid syntax: .2ce58322c0c02b51d655 [polyfills-es5.2ce58322c0c02b51d655.js:1,13]
    at ee (C:\Users\user\Desktop\IHM Repos\elcano-web-elements\elcano-web-elements\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:19541)
    at m (C:\Users\user\Desktop\IHM Repos\elcano-web-elements\elcano-web-elements\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:20854)
    at h (C:\Users\user\Desktop\IHM Repos\elcano-web-elements\elcano-web-elements\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:21806)
    at Object.H [as input] (C:\Users\user\Desktop\IHM Repos\elcano-web-elements\elcano-web-elements\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:26010)
    at a (C:\Users\user\Desktop\IHM Repos\elcano-web-elements\elcano-web-elements\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:28003)
    at s (C:\Users\user\Desktop\IHM Repos\elcano-web-elements\elcano-web-elements\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:28057)
    at B (C:\Users\user\Desktop\IHM Repos\elcano-web-elements\elcano-web-elements\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:40050)
    at G (C:\Users\user\Desktop\IHM Repos\elcano-web-elements\elcano-web-elements\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:42555)
    at ge (C:\Users\user\Desktop\IHM Repos\elcano-web-elements\elcano-web-elements\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:48272)
    at Ae (C:\Users\user\Desktop\IHM Repos\elcano-web-elements\elcano-web-elements\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:48998)
`

What am I doing wrong? I only have updated from angular 8 to angular 9 using it's manual.

**Comment by just-jeb** [comment]
Why do you have `externals: replace`?

**Comment by ssg127** [comment]
@just-jeb, what is the problem? I have this before and It world.

**Comment by clm2609** [comment]
Hi, I have a similar problem, after looking through some documentation I tried to build with the --optimization=false flag to disable Terser. This allowed me to see another error (which I believe is the real problem):

```
Generating ES5 bundles for differential loading...
An unhandled exception occurred: /home/lobo/Telefonica/ng-cyber-theme/polyfills-es5.js: Invalid left-hand side in assignment expression (1:0)

> 1 | polyfills-es5.js =
    | ^
  2 | (window["myElements-e3313190-e2c8-11ea-8839-d803afcb9c89"] = window["myElements-e3313190-e2c8-11ea-8839-d803afcb9c89"] || []).push([["polyfills-es5"],{
  3 | 
  4 | /***/ "./node_modules/@angular-devkit/build-angular/node_modules/core-js/es/date/index.js":
```

My custom webpack configuration:

```
var uuidv1 = require('uuidv1');
module.exports = {
  output: {
    jsonpFunction: 'myElements-' + uuidv1(),
    library: 'xxxxxxx'
  }
};
```

**Comment by ssg127** [comment]
@clm2609 has you solved it?

**Comment by just-jeb** [comment]
@clm2609 does it work when you run it with Angular builder coming out of the box?

**Comment by clm2609** [comment]
@just-jeb It does compile when I remove the customWebpackConfig from angular.json but it will break when I try to use it because I'm using custom webpack to compile my angular library into webcomponents. To do that I looked up the following tutorial:

https://medium.com/angular-in-depth/how-to-compile-your-angular-components-library-into-web-components-47ff0ac73bd7

If you check it you will see I need the custom configuration to avoid this error:
![error](https://user-images.githubusercontent.com/3873955/91825667-d9884200-ec3c-11ea-8456-e410da281fdd.png)

Any idea why this may be happening?

@ssg127 Sorry, I've been unable to work it out.

**Comment by just-jeb** [comment]
Frankly I have no idea how your custom webpack config may result in the wrong polyfill syntax. I don't see anything that could cause it. 
What's the difference in the content of `polyfill-es5.js` when you run it without/with custom webpack config?

**Comment by ssg127** [comment]
@just-jeb more details:

`polyfills-es5.js: Invalid left-hand side in assignment expression (1:0)

> 1 | polyfills-es5.js =
    | ^
  2 | (window["webpackJsonpElcanoElements"] = window["webpackJsonpElcanoElements"] || []).push([["polyfills-es5"],{
  3 | 
  4 | /***/ "./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es5-jit-polyfills.js":
See "C:\Users\sasg\AppData\Local\Temp\ng-GdoomI\angular-errors.log" for further details.
`

Log file:
`[error] SyntaxError: C:\XXXXXX\polyfills-es5.js: Invalid left-hand side in assignment expression (1:0)

[0m[31m[1m>[22m[39m[90m 1 | [39mpolyfills[33m-[39mes5[33m.[39mjs [33m=[39m[0m
[0m [90m   | [39m[31m[1m^[22m[39m[0m
[0m [90m 2 | [39m(window[[32m"webpackXXXXXXElements"[39m] [33m=[39m window[[32m"webpackXXXXXXElements"[39m] [33m||[39m [])[33m.[39mpush([[[32m"polyfills-es5"[39m][33m,[39m{[0m
[0m [90m 3 | [39m[0m
[0m [90m 4 | [39m[90m/***/[39m [32m"./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es5-jit-polyfills.js"[39m[33m:[39m[0m
    at Parser._raise (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:763:17)
    at Parser.raiseWithData (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:756:17)
    at Parser.raise (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:750:17)
    at Parser.checkLVal (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:9432:16)
    at Parser.parseMaybeAssign (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:9590:12)
    at Parser.parseExpression (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:9520:23)
    at Parser.parseStatementContent (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11479:23)
    at Parser.parseStatement (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11348:17)
    at Parser.parseBlockOrModuleBlockBody (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11930:25)
    at Parser.parseBlockBody (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11916:10)
    at Parser.parseTopLevel (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11279:10)
    at Parser.parse (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:12984:10)
    at parse (C:\XXXXXX\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:13037:38)
    at parser (C:\XXXXXX\node_modules\@babel\core\lib\parser\index.js:54:34)
    at parser.next (<anonymous>)
    at normalizeFile (C:\XXXXXX\node_modules\@babel\core\lib\transformation\normalize-file.js:93:38)

`

**Comment by just-jeb** [comment]
I understand the problem, `polyfills-es5.js = 'blah'` is not a valid syntax in JS.  
I wonder what does the content of `polyfills-es5.js` look like when it's compiled without the custom config.

**Comment by ssg127** [comment]
@just-jeb where can I find `polyfills-es5.js`? Because in dist folder is always empty, the build doesn't end.

**Comment by ssg127** [comment]
If in `tsconfig.json` I put in `compilerOptions` `"target": "es2015"` it works. I don't know why.

**Comment by clm2609** [comment]
@ssg127 You seem to be doing something similar with Angular Elements. Do these work when compiling with that target? I think when I last tried to build with that target webcomponents didn't work properly.

**Comment by ssg127** [comment]
@just-jeb @clm2609 If I remove `library` in `extra-webpack.config` it works.

**Comment by clm2609** [comment]
Thanks @ssg127 After trying it out in my test project it does seem to work. As soon as I try it in a more complex environment I'll update the thread.
