### ISSUE TITLE
Build outputs between `@angular-devkit/build-angular` and `@angular-builders/custom-webpack` are different

### ISSUE THREAD

**Issue by muuvmuuv** [just-jeb/angular-builders#894]
## Describe the Bug

I currently have an issue with web workers that angular tries to always compiler just one at a time which results in duplicated code files (). Then I tried to find out where this is coming from and started a new angular project and added step by step what I am doing with web workers in my app.

At the end after adding custom-webpack I got the below error and also recognized another thing: the build output at all is completely different to the new ng11 build output. My error went away when I removed `custom-webpack`, so I guess just an internal update from the part where it passes the config to the original angular compiler is needed.

<details>
<summary>Details</summary>

```console
❯ npm run build 

> test@0.0.0 build /Users/marvinheilemann/Desktop/test-von-donnerstag
> ng build


WARNING in /Users/marvinheilemann/Desktop/test-von-donnerstag/src/environments/environment.ts depends on 'zone.js/dist/zone-error'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

ERROR in ./src/app/workers/two.worker.ts (./node_modules/worker-plugin/dist/loader.js?name=1!./src/app/workers/two.worker.ts)
Module build failed (from ./node_modules/worker-plugin/dist/loader.js):
Error: TypeError: Cannot read property 'getOptionsDiagnostics' of undefined
    at AngularCompilerPlugin._emit (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:1037:54)
    at AngularCompilerPlugin._update (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:883:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AngularCompilerPlugin._make (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:760:13)

    at /Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:886:79
    at Object.reportDiagnostics (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/@ngtools/webpack/src/diagnostics.js:131:9)
    at AngularCompilerPlugin._update (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:886:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AngularCompilerPlugin._make (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:760:13)
 @ ./src/app/app.component.ts 1:0-134
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts2m

ERROR in TypeError: Cannot read property 'getOptionsDiagnostics' of undefined
    at AngularCompilerPlugin._emit (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:1037:54)
    at AngularCompilerPlugin._update (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:883:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AngularCompilerPlugin._make (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:760:13)


ERROR in TypeError: Cannot read property 'kind' of undefined
    at areDeclarationFlagsIdentical (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:72438:71)
    at checkVariableLikeDeclaration (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:72408:22)
    at checkVariableDeclaration (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:72455:20)
    at checkSourceElementWorker (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:75060:28)
    at checkSourceElement (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:74907:17)
    at Object.forEach (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:382:30)
    at checkVariableStatement (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:72465:16)
    at checkSourceElementWorker (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:75029:28)
    at checkSourceElement (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:74907:17)
    at Object.forEach (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:382:30)
    at checkSourceFileWorker (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:75246:20)
    at checkSourceFile (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:75214:13)
    at getDiagnosticsWorker (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:75302:17)
    at Object.getDiagnostics (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:75288:24)
    at /Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:103754:85
    at runWithCancellationToken (/Users/marvinheilemann/Desktop/test-von-donnerstag/node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js:103716:24)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.0.0 build: `ng build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marvinheilemann/.npm/_logs/2020-12-07T13_31_33_594Z-debug.log
```

</details>

## Minimal Reproduction

https://github.com/muuvmuuv/angular-worker-issue

## Expected Behavior

Same output as in standard angular builder.

## Screenshots

`"builder": "@angular-devkit/build-angular:browser"`

![Bildschirmfoto 2020-12-07 um 14 31 13](https://user-images.githubusercontent.com/11534760/101356904-05990c00-3899-11eb-802d-ca6a648a3238.png)

`"builder": "@angular-builders/custom-webpack:browser",`

*Normally*

<img width="329" alt="Bildschirmfoto 2020-12-07 um 14 31 55" src="https://user-images.githubusercontent.com/11534760/101356919-0af65680-3899-11eb-8213-5f32ce43ec2c.png">

*With web workers enabled*

![Bildschirmfoto 2020-12-07 um 14 32 07](https://user-images.githubusercontent.com/11534760/101356921-0c278380-3899-11eb-9b34-6ad2abf72d1c.png)

## Environment

<pre><code>
Libs
see project

For Tooling issues:
- Node version: v14.15.1
- Platform: Mac 10.15.7

Others:

</code></pre>

**Comment by muuvmuuv** [comment]
OK. I see that *custom-webpack* is using `"@angular-devkit/build-angular": ">=0.1000.0 < 0.1100.0",`. Is it possible to upgrade that to the latest devkit?

**Comment by muuvmuuv** [comment]
Tried to force resolutions to the latest possible which still results to the same as above. So I guess it is not only the older devkit.

**Comment by briananderson1222** [comment]
@muuvmuuv `npm i @angular-builders/custom-webpack@next` to get the Angular 11 version (currently in beta)

**Comment by muuvmuuv** [comment]
Update the repo. Now it works! Thank you :)

**Comment by just-jeb** [comment]
@all-contributors please add @briananderson1222 for answering questions.
